name: Lint And Format

on: [push]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    name: Check Codebase
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install App
        run: bun install

      - name: Lint with ESLint
        run: bun lint

      - name: Format with Prettier
        run: bun format
